---
deployment:
  tasks:
    # Show what directory we're starting in
    - export DEPLOYPATH=/home/ecclesia/public_html
    - echo "Starting deployment from $(pwd)"
    - echo "Target deployment path is $DEPLOYPATH"
    
    # Check Node and npm versions
    - /usr/bin/node --version
    - /usr/bin/npm --version
    
    # Install dependencies
    - /usr/bin/npm ci --omit=dev
    
    # Build the static site
    - /usr/bin/npm run build
    
    # Verify build directory exists and show contents
    - echo "Build directory contents:"
    - /bin/ls -la build/
    
    # Clear public_html (preserve cgi-bin and any hidden files)
    - /bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name 'cgi-bin' ! -name '.*' -exec rm -rf {} +
    
    # Copy all built files to public_html
    - /bin/cp -R build/* $DEPLOYPATH/
    - /bin/cp -R build/.??* $DEPLOYPATH/ 2>/dev/null || true
    
    # Copy .htaccess explicitly
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    
    # Verify deployment
    - echo "Deployed files:"
    - /bin/ls -la $DEPLOYPATH/
    
    # Set correct permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - /bin/chmod 644 $DEPLOYPATH/.htaccess